superset:
  url:
  user:
  password:
  dashboard_base_path: "/superset/dashboard"
  dashboard_querystring: "standalone=1"
  dashboard_delay_sec: 60
  headless: true
  page_timeout_ms: 180000
  retry_on_fail: 1
  per_chart_retries: 2
  provider: db
  total_allocated_running_sec: 7200 # 2 hours
